[package]
name = "infrarust"
version = "1.0.2"
edition = "2021"
authors = ["Shadowner"]
description = "A Rust adaptation of the Infrared Minecraft proxy"
license = "AGPL-3.0-only"
homepage = "https://infrarust.dev"
repository = "https://github.com/shadowner/infrarust"
readme = "README.md"
categories = ["network-programming", "command-line-utilities"]
keywords = ["networking", "proxy", "minecraft", "gameserver", "protocol"]
exclude = [
    "docs/*",
    "!docs/public/img/logo.svg",
    "docker/*",
    "config_examples/*",
    ".github/*",
    ".vscode/*",
]

[dependencies]
# Async runtime
tokio = { version = "1.32", features = ["full"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
libdeflater = "1.23.0"
num-bigint = "0.4.6"
num-traits = "0.2.19"
base64 = "0.22.1"
bytes = "1.9.0"
generic-array = "1.2.0"

# Networking
proxy-protocol = "0.5"
ipnetwork = "0.21.1"
reqwest = { version = "0.12.2", features = ["json", "rustls-tls"], default-features = false }

# Utilities
log = {version = "0.4.25", features = ["release_max_level_info"]}
uuid = { version = "1.12.0", features = ["v4", "serde"] }
xxhash-rust = { version = "0.8", features = ["xxh64"] } 
wildmatch = "2.1"
walkdir = "2.3"

# Error handling
thiserror = "2.0.11"
parking_lot = "0.12.3"
env_logger = "0.11.6"
async-trait = "0.1.85"

# Encryption 
aes = "0.8.4"
cfb8 = "0.8.1"
rsa = "0.9.6"
rsa-der = "0.3.0"
rand = "0.8"
sha1 = "0.10"
hex = "0.4"

# Command line parsing for bin
clap = { version = "4.4", features = ["derive"] }
notify = "8.0.0"
lazy_static = "1.5.0"

[dev-dependencies]
tempfile = "3.8"
env_logger = "0.11.6"

[features]
default = []
telemetry = [] # Planned amelioration for metrics and monitoring
dashboard = [] # Planned amelioration for a web dashboard
api = [] # Planned amelioration for a REST API

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

[profile.dev]
opt-level = 0
debug = true     

[[bin]]
name = "infrarust"
path = "src/bin/infrarust.rs"
