[workspace]
resolver = "2"
members = ["crates/infrarust*"]

[workspace.package]
version = "1.2.0"
edition = "2024"
authors = ["Shadowner"]
repository = "https://github.com/shadowner/infrarust"
license = "AGPL-3.0-only"
homepage = "https://infrarust.dev"
