[package]
name = "infrarust"
version = "1.1.1"
edition = "2021"
authors = ["Shadowner"]
description = "A Rust adaptation of the Infrared Minecraft proxy"
license = "AGPL-3.0-only"
homepage = "https://infrarust.dev"
repository = "https://github.com/shadowner/infrarust"
readme = "README.md"
categories = ["network-programming", "command-line-utilities"]
keywords = ["networking", "proxy", "minecraft", "gameserver", "protocol"]
exclude = [
    "docs/*",
    "!docs/public/img/logo.svg",
    "docker/*",
    "config_examples/*",
    ".github/*",
    ".vscode/*",
]

[dependencies]
# Async & Runtime
tokio = { version = "1.32", features = ["full"] }
async-trait = "0.1.85"

# Logging & Telemetry
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "fmt"] }
tracing-opentelemetry = "0.28.0"
opentelemetry = { version = "0.27.1", features = ["metrics"] }
opentelemetry_sdk = { version = "0.27.1", features = ["metrics", "rt-tokio"] }
opentelemetry-appender-log = { version = "0.27.0" }
opentelemetry-prometheus = "0.27.0"
opentelemetry-stdout = "0.27.0"
opentelemetry-otlp = { version = "0.27.0", features = ["grpc-tonic", "trace", "metrics", "logs", "tokio"] }
opentelemetry-semantic-conventions = "0.27.0"

# Serialization & Data Formats
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
base64 = "0.22.1"
bytes = "1.9.0"

# Networking & Protocol
proxy-protocol = "0.5"
ipnetwork = "0.21.0"
reqwest = { version = "0.12.2", features = ["json", "rustls-tls"], default-features = false }

# Cryptography & Security
aes = "0.8.4"
cfb8 = "0.8.1"
rsa = "0.9.6"
rsa-der = "0.3.0"
rand = "0.8"
sha1 = "0.10"
hex = "0.4"

# Data Structures & Algorithms
num-bigint = "0.4.6"
num-traits = "0.2.19"
generic-array = "1.2.0"
xxhash-rust = { version = "0.8", features = ["xxh64"] }

# System & Resource Management
sysinfo = "0.33.1"
libdeflater = "1.23.0"

# Utility & Helper Libraries
uuid = { version = "1.12.1", features = ["v4", "serde"] }
parking_lot = "0.12.3"
lazy_static = "1.5.0"
walkdir = "2.3"
wildmatch = "2.1"
notify = "8.0.0"

# Error Handling
thiserror = "2.0.11"
anyhow = "1.0.95"

# CLI & Configuration
clap = { version = "4.5.28", features = ["derive"] }
env_logger = "0.11.6"

[dev-dependencies]
tempfile = "3.16.0"
env_logger = "0.11.6"

[features]
default = []
telemetry = [] # TODO Permit a build not include any telemtry code at all
dashboard = [] # Planned amelioration for a web dashboard
api = []       # Planned amelioration for a REST API

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

[profile.dev]
opt-level = 0
debug = true

[[bin]]
name = "infrarust"
path = "src/bin/infrarust.rs"
