//! Entry lists for protocol >= 766 (Minecraft 1.20.5+).

use super::LimboRegistryEntries;

pub(crate) static ENTRIES: LimboRegistryEntries = LimboRegistryEntries {
    dimension_types: &["minecraft:the_end"],
    biomes: &["minecraft:plains"],
    chat_types: &["minecraft:chat"],

    // All vanilla damage types (extracted from 1.21.11).
    damage_types: &[
        "minecraft:arrow",
        "minecraft:bad_respawn_point",
        "minecraft:cactus",
        "minecraft:campfire",
        "minecraft:cramming",
        "minecraft:dragon_breath",
        "minecraft:drown",
        "minecraft:dry_out",
        "minecraft:ender_pearl",
        "minecraft:explosion",
        "minecraft:fall",
        "minecraft:falling_anvil",
        "minecraft:falling_block",
        "minecraft:falling_stalactite",
        "minecraft:fireball",
        "minecraft:fireworks",
        "minecraft:fly_into_wall",
        "minecraft:freeze",
        "minecraft:generic",
        "minecraft:generic_kill",
        "minecraft:hot_floor",
        "minecraft:in_fire",
        "minecraft:in_wall",
        "minecraft:indirect_magic",
        "minecraft:lava",
        "minecraft:lightning_bolt",
        "minecraft:mace_smash",
        "minecraft:magic",
        "minecraft:mob_attack",
        "minecraft:mob_attack_no_aggro",
        "minecraft:mob_projectile",
        "minecraft:on_fire",
        "minecraft:out_of_world",
        "minecraft:outside_border",
        "minecraft:player_attack",
        "minecraft:player_explosion",
        "minecraft:sonic_boom",
        "minecraft:spear",
        "minecraft:spit",
        "minecraft:stalagmite",
        "minecraft:starve",
        "minecraft:sting",
        "minecraft:sweet_berry_bush",
        "minecraft:thorns",
        "minecraft:thrown",
        "minecraft:trident",
        "minecraft:unattributed_fireball",
        "minecraft:wind_charge",
        "minecraft:wither",
        "minecraft:wither_skull",
    ],

    painting_variants: &["minecraft:kebab"],
    wolf_variants: &["minecraft:pale"],
    banner_patterns: &["minecraft:base"],
    trim_materials: &["minecraft:iron"],
    trim_patterns: &["minecraft:coast"],

    jukebox_songs: Some(&["minecraft:13"]),
    enchantments: Some(&["minecraft:protection"]),
    instruments: Some(&["minecraft:ponder_goat_horn"]),
    wolf_sound_variants: Some(&["minecraft:classic"]),
    pig_variants: Some(&["minecraft:temperate"]),
    frog_variants: Some(&["minecraft:temperate"]),
    cat_variants: Some(&["minecraft:tabby"]),
    cow_variants: Some(&["minecraft:temperate"]),
    chicken_variants: Some(&["minecraft:temperate"]),

    zombie_nautilus_variants: Some(&["minecraft:temperate"]),
    test_environments: Some(&["minecraft:default"]),
    test_instances: Some(&["minecraft:always_pass"]),
    dialogs: Some(&["minecraft:server_links"]),
    timelines: Some(&["minecraft:day"]),
};
