[package]
name = "infrarust_server_manager"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "A Minecraft server manager that handles API monitoring and system commands"

[dependencies]
# Async runtime
tokio = { version = "1.28", features = ["full"] }

# Networking and API
reqwest = { version = "0.12.15", features = ["json"] }
async-trait = "0.1.68"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Error handling
thiserror = "2.0.12"

# Logging
env_logger = "0.11.8"
tracing = "0.1.41"
pterodactyl_api = "0.2.0"

[dev-dependencies]
tokio-test = "0.4"
