server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"  # Maintenant uniquement accessible en interne
        http:
          endpoint: "0.0.0.0:4318"  # Maintenant uniquement accessible en interne

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/blocks

compactor:
  compaction:
    block_retention: 24h

overrides:
  metrics_generator_processors: [service-graphs, span-metrics]
