{
 "title": "Infrarust Proxy Monitoring",
 "tags": [
  "minecraft",
  "proxy",
  "monitoring",
  "infrarust"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(infrarust_minecraft_players, server)"
    }
   },
   { "name": "session", "label": "Connection Session", "query": { "query": "label_values(session_id)" } }
  ]
 },
 "panels": [
  { "title": "Vue d'ensemble", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(infrarust_system_cpu_percent_sum[1m]) / rate(infrarust_system_cpu_percent_count[1m])"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(infrarust_connections_active)"
    }
   ]
  },
  {
   "title": "Total Data Transfered",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (direction) (infrarust_network_bytes_total)\r\n"
    }
   ]
  },
  {
   "title": "Mean status request",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(infrarust_requests_rate_total[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Players by server",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (server) (infrarust_minecraft_players)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(infrarust_system_memory_bytes_sum[1m]) / rate(infrarust_system_memory_bytes_count[1m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total active Configuration",
   "type": "stat",
   "description": "Number of configurations loaded and active by the differents config Providers.",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (infrarust_backends_active_servers)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Performances Réseau", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Real-time Network Transfer Rate by Server Configuration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(\r\n  rate(infrarust_network_bytes_total[1m])\r\n  * on(session_id)\r\n  group_left(config_id)\r\n  (infrarust_backends_requests_total > 0)\r\n) by (config_id)"
    }
   ]
  },
  {
   "title": "Real-time Player Bandwidth Usage",
   "type": "timeseries",
   "description": "Shows the current network transfer rate for each player across all servers. Higher values indicate players transferring more data through the proxy",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(10,\r\n  sum(\r\n    rate(infrarust_network_bytes_total[1m])\r\n    * on(session_id)\r\n    group_left(username)\r\n    (infrarust_minecraft_players{username=~\".+\"} > 0)\r\n  ) by (username)\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Data Usage by Server (Requests included)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(\r\n  topk(10,\r\n    sum(\r\n      infrarust_network_bytes_total\r\n      * on(session_id)\r\n      group_left(config_id, server)\r\n      (infrarust_backends_requests_total > 0)\r\n    ) by (config_id, server)\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Network Consumers by Player",
   "type": "bargauge",
   "description": "Displays the players who have transferred the most data through the proxy, helping identify high-bandwidth users",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,\r\n  sum(infrarust_network_bytes_total) by (session_id) \r\n  * on(session_id) \r\n  group_right \r\n  infrarust_minecraft_players{username=~\".+\"}\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Latence by Server",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(server) (infrarust_backends_latency_milliseconds_sum)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Servers with errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(config_id) (increase(infrarust_backends_errors_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Errors",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "count by (config_id, error) (increase(infrarust_backends_errors_total[$__range]))"
    }
   ]
  },
  {
   "title": "Failed status request servers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (server, config_id) (\r\n  last_over_time(infrarust_backends_latency_milliseconds_sum{success=\"false\"}[$__range])\r\n  > 0\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } }
 ]
}