name: Latest Build

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
          
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
          
      - name: Check formatting
        run: cargo fmt -- --check
        
      - name: Run clippy
        run: cargo clippy -- -D warnings
        
      - name: Run tests
        run: cargo test

      - name: Build
        run: cargo build --release
        
      - name: Rename binary
        run: mv target/release/infrarust target/release/infrarust-latest-linux
          
      - name: Upload latest build
        uses: actions/upload-artifact@v4
        with:
          name: latest-build
          path: target/release/infrarust-latest